// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;

// -------------------
// Customized enums
// -------------------

public enum ETest
{
	EA,
	EB,
	EC,
}

// -------------------
// Customized structs
// -------------------

public struct StructTest
{
	public bool a;
}
