// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_HEADERS_H_
#define _BEHAVIAC_HEADERS_H_

#include "behaviac/behaviac.h"

// You should set the agent header files of your game when exporting cpp files on the behaviac editor:
#include "../../../Agent/AgentArrayAccessTest.h"
#include "../../../Agent/AgentNodeTest.h"
#include "../../../Agent/CustomPropertyAgent.h"
#include "../../../Agent/EmployeeParTestAgent.h"
#include "../../../Agent/FSMAgentTest.h"
#include "../../../Agent/HTNAgentHouse.h"
#include "../../../Agent/HTNAgentHouseBase.h"
#include "../../../Agent/HTNAgentTravel.h"
#include "../../../Agent/ParTestAgent.h"
#include "../../../Agent/ParTestAgentBase.h"
#include "../../../Agent/ParTestRegNameAgent.h"
#include "../../../Agent/PreconEffectorAgent.h"
#include "../../../Agent/PropertyReadonlyAgent.h"
#include "../../../Agent/UnitTestTypes.h"

// The following agent header files is generated automatically:

#endif // _BEHAVIAC_HEADERS_H_
