// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_CUSTOMIZED_TYPES_H_
#define _BEHAVIAC_CUSTOMIZED_TYPES_H_

#include "behaviac/agent/agent.h"

// -------------------
// Customized enums
// -------------------

enum ETest
{
	EA,
	EB,
	EC,
};

// -------------------
// Customized structs
// -------------------

struct StructTest
{
	bool a;

DECLARE_BEHAVIAC_STRUCT(StructTest);
};

DECLARE_BEHAVIAC_ENUM(ETest, ETest);

BEHAVIAC_DECLARE_TYPE_VECTOR_HANDLER(StructTest);
#endif // _BEHAVIAC_CUSTOMIZED_TYPES_H_
