// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#include "behaviac/agent/registermacros.h"
#include "behaviac_customized_types.h"

// -------------------
// Customized enums
// -------------------


BEHAVIAC_BEGIN_ENUM(ETest, ETest)
{
	BEHAVIAC_ENUMCLASS_DISPLAY_INFO(L"ETest", L"ETest");

	BEHAVIAC_ENUM_ITEM(EA, "EA");
	BEHAVIAC_ENUM_ITEM(EB, "EB");
	BEHAVIAC_ENUM_ITEM(EC, "EC");
}
BEHAVIAC_END_ENUM()

// -------------------
// Customized structs
// -------------------


BEHAVIAC_BEGIN_STRUCT(StructTest)
{
	BEHAVIAC_STRUCT_DISPLAYNAME(L"StructTest");
	BEHAVIAC_STRUCT_DESC(L"StructTest");

	BEHAVIAC_REGISTER_STRUCT_PROPERTY(a).DISPLAYNAME(L"a").DESC(L"a");
}
BEHAVIAC_END_STRUCT()
