// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_HEADERS_H_
#define _BEHAVIAC_HEADERS_H_

#include "behaviac/behaviac.h"

// You should set the agent header files of your game when exporting cpp files on the behaviac editor:
#include "../../../../../StructExtended.h"

// The following agent header files is generated automatically:
#include "AgentTest.h"

#endif // _BEHAVIAC_HEADERS_H_
