// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"
#include "behaviac_customized_types.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }

	inline void Set_AgentTest_Property1(Agent* self, int value) { ((AgentTest*)self)->_set_Property1(value); };
	inline const void* Get_AgentTest_Property1(Agent* self) { return &((AgentTest*)self)->_get_Property1(); };

	inline void Set_AgentTest_Property2(Agent* self, float value) { ((AgentTest*)self)->_set_Property2(value); };
	inline const void* Get_AgentTest_Property2(Agent* self) { return &((AgentTest*)self)->_get_Property2(); };

	inline void FunctionPointer_AgentTest_LogMessage(char* param0) { AgentTest::LogMessage(param0); }
	inline bool FunctionPointer_AgentTest_Method(Agent* self, int param0) { return ((AgentTest*)self)->Method(param0); }
	inline void FunctionPointer_AgentTest_Method2(Agent* self) { ((AgentTest*)self)->Method2(); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
