// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#include "behaviac/agent/registermacros.h"
#include "behaviac_customized_types.h"

// -------------------
// Customized enums
// -------------------

BEHAVIAC_BEGIN_ENUM(EnumTest, EnumTest)
{
	BEHAVIAC_ENUMCLASS_DISPLAY_INFO(L"EnumTest", L"EnumTest");

	BEHAVIAC_ENUM_ITEM(AAA, "AAA");
	BEHAVIAC_ENUM_ITEM(BBB, "BBB");
	BEHAVIAC_ENUM_ITEM(CCC, "CCC");
}
BEHAVIAC_END_ENUM()

// -------------------
// Customized structs
// -------------------

BEHAVIAC_BEGIN_STRUCT(StructTest)
{
	BEHAVIAC_STRUCT_DISPLAYNAME(L"StructTest");
	BEHAVIAC_STRUCT_DESC(L"StructTest");

	BEHAVIAC_REGISTER_STRUCT_PROPERTY(Member1).DISPLAYNAME(L"Member1").DESC(L"Member1");
	BEHAVIAC_REGISTER_STRUCT_PROPERTY(Member2).DISPLAYNAME(L"Member2").DESC(L"Member2");
	BEHAVIAC_REGISTER_STRUCT_PROPERTY(Member3).DISPLAYNAME(L"Member3").DESC(L"Member3");
}
BEHAVIAC_END_STRUCT()
