// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#include "behaviac_agent_meta.h"

namespace behaviac
{
	class CppBehaviorLoaderImplement : CppBehaviorLoader
	{
	public:
		CppBehaviorLoaderImplement()
		{
			AgentMeta::SetInstance(this);
		}

		virtual ~CppBehaviorLoaderImplement()
		{
		}

		virtual bool load()
		{
			AgentMeta::SetTotalSignature(4015517298u);

			AgentMeta* meta = NULL;
			BEHAVIAC_UNUSED_VAR(meta);

			// behaviac::Agent
			meta = BEHAVIAC_NEW AgentMeta(2472787040u);
			AgentMeta::GetAgentMetas()[1770892321u] = meta;
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_behaviac_Agent_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_behaviac_Agent_VectorAdd));
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<IList&>(FunctionPointer_behaviac_Agent_VectorClear));
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CAgentStaticMethod_2< bool, IList&, System::Object& >(FunctionPointer_behaviac_Agent_VectorContains));
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CAgentStaticMethod_1< int, IList& >(FunctionPointer_behaviac_Agent_VectorLength));
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_behaviac_Agent_VectorRemove));

			// framework::GameObject
			meta = BEHAVIAC_NEW AgentMeta(4128499417u);
			AgentMeta::GetAgentMetas()[1407918510u] = meta;
			meta->RegisterMemberProperty(2436539256u, BEHAVIAC_NEW CMemberProperty< long >("age", Set_framework_GameObject_age, Get_framework_GameObject_age));
			meta->RegisterMemberProperty(713213677u, BEHAVIAC_NEW CMemberProperty< unsigned int >("HP", Set_framework_GameObject_HP, Get_framework_GameObject_HP));
			meta->RegisterMethod(828258197u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_framework_GameObject_alignedWithPlayer));
			meta->RegisterMethod(1552598362u, BEHAVIAC_NEW CAgentMethod< float >(FunctionPointer_framework_GameObject_distanceToPlayer));
			meta->RegisterMethod(1340929876u, BEHAVIAC_NEW CAgentMethodVoid_1<int>(FunctionPointer_framework_GameObject_GoStraight));
			meta->RegisterMethod(4083678003u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_framework_GameObject_playerIsAligned));
			meta->RegisterMethod(3456887588u, BEHAVIAC_NEW CAgentMethod_1< bool, float >(FunctionPointer_framework_GameObject_projectileNearby));
			meta->RegisterMethod(966632266u, BEHAVIAC_NEW CAgentMethod_1< int, float >(FunctionPointer_framework_GameObject_TurnTowardsTarget));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_framework_GameObject_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_framework_GameObject_VectorAdd));
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<IList&>(FunctionPointer_framework_GameObject_VectorClear));
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CAgentStaticMethod_2< bool, IList&, System::Object& >(FunctionPointer_framework_GameObject_VectorContains));
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CAgentStaticMethod_1< int, IList& >(FunctionPointer_framework_GameObject_VectorLength));
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_framework_GameObject_VectorRemove));

			// framework::Projectile
			meta = BEHAVIAC_NEW AgentMeta(2747484356u);
			AgentMeta::GetAgentMetas()[2189145894u] = meta;
			meta->RegisterMemberProperty(2436539256u, BEHAVIAC_NEW CMemberProperty< long >("age", Set_framework_Projectile_age, Get_framework_Projectile_age));
			meta->RegisterMemberProperty(713213677u, BEHAVIAC_NEW CMemberProperty< unsigned int >("HP", Set_framework_Projectile_HP, Get_framework_Projectile_HP));
			meta->RegisterMethod(828258197u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_framework_Projectile_alignedWithPlayer));
			meta->RegisterMethod(1552598362u, BEHAVIAC_NEW CAgentMethod< float >(FunctionPointer_framework_Projectile_distanceToPlayer));
			meta->RegisterMethod(1340929876u, BEHAVIAC_NEW CAgentMethodVoid_1<int>(FunctionPointer_framework_Projectile_GoStraight));
			meta->RegisterMethod(4083678003u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_framework_Projectile_playerIsAligned));
			meta->RegisterMethod(3456887588u, BEHAVIAC_NEW CAgentMethod_1< bool, float >(FunctionPointer_framework_Projectile_projectileNearby));
			meta->RegisterMethod(966632266u, BEHAVIAC_NEW CAgentMethod_1< int, float >(FunctionPointer_framework_Projectile_TurnTowardsTarget));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_framework_Projectile_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_framework_Projectile_VectorAdd));
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<IList&>(FunctionPointer_framework_Projectile_VectorClear));
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CAgentStaticMethod_2< bool, IList&, System::Object& >(FunctionPointer_framework_Projectile_VectorContains));
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CAgentStaticMethod_1< int, IList& >(FunctionPointer_framework_Projectile_VectorLength));
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_framework_Projectile_VectorRemove));

			// framework::Ship
			meta = BEHAVIAC_NEW AgentMeta(804937787u);
			AgentMeta::GetAgentMetas()[1271307080u] = meta;
			meta->RegisterMemberProperty(2436539256u, BEHAVIAC_NEW CMemberProperty< long >("age", Set_framework_Ship_age, Get_framework_Ship_age));
			meta->RegisterMemberProperty(713213677u, BEHAVIAC_NEW CMemberProperty< unsigned int >("HP", Set_framework_Ship_HP, Get_framework_Ship_HP));
			meta->RegisterMethod(2990669001u, BEHAVIAC_NEW CAgentMethod_1< behaviac::EBTStatus, bool >(FunctionPointer_framework_Ship_checkresult));
			meta->RegisterMethod(1098272789u, BEHAVIAC_NEW CAgentMethodVoid_1<float>(FunctionPointer_framework_Ship_DestroyAllNearbyProjectiles));
			meta->RegisterMethod(3771923015u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_framework_Ship_Fire));
			meta->RegisterMethod(1143237114u, BEHAVIAC_NEW CAgentMethod< double >(FunctionPointer_framework_Ship_GetConstDoubleValue));
			meta->RegisterMethod(2224959841u, BEHAVIAC_NEW CAgentMethod< float >(FunctionPointer_framework_Ship_GetConstFloatValue));
			meta->RegisterMethod(2770306674u, BEHAVIAC_NEW CAgentMethod< float >(FunctionPointer_framework_Ship_getXPosition));
			meta->RegisterMethod(1256058188u, BEHAVIAC_NEW CAgentMethod< float >(FunctionPointer_framework_Ship_getYPosition));
			meta->RegisterMethod(2536101085u, BEHAVIAC_NEW CAgentMethod_3< bool, float, float, float >(FunctionPointer_framework_Ship_GotoPoint));
			meta->RegisterMethod(244921611u, BEHAVIAC_NEW CAgentMethod_3< bool, float, float, float >(FunctionPointer_framework_Ship_GotoPointRelative));
			meta->RegisterMethod(828258197u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_framework_Ship_alignedWithPlayer));
			meta->RegisterMethod(1552598362u, BEHAVIAC_NEW CAgentMethod< float >(FunctionPointer_framework_Ship_distanceToPlayer));
			meta->RegisterMethod(1340929876u, BEHAVIAC_NEW CAgentMethodVoid_1<int>(FunctionPointer_framework_Ship_GoStraight));
			meta->RegisterMethod(4083678003u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_framework_Ship_playerIsAligned));
			meta->RegisterMethod(3456887588u, BEHAVIAC_NEW CAgentMethod_1< bool, float >(FunctionPointer_framework_Ship_projectileNearby));
			meta->RegisterMethod(966632266u, BEHAVIAC_NEW CAgentMethod_1< int, float >(FunctionPointer_framework_Ship_TurnTowardsTarget));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_framework_Ship_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_framework_Ship_VectorAdd));
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<IList&>(FunctionPointer_framework_Ship_VectorClear));
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CAgentStaticMethod_2< bool, IList&, System::Object& >(FunctionPointer_framework_Ship_VectorContains));
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CAgentStaticMethod_1< int, IList& >(FunctionPointer_framework_Ship_VectorLength));
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_framework_Ship_VectorRemove));

			// framework::WorldState
			meta = BEHAVIAC_NEW AgentMeta(1074775610u);
			AgentMeta::GetAgentMetas()[2541539938u] = meta;
			meta->RegisterMemberProperty(2389310492u, BEHAVIAC_NEW CMemberProperty< unsigned int >("HealthHP", Set_framework_WorldState_HealthHP, Get_framework_WorldState_HealthHP));
			meta->RegisterMemberProperty(404245629u, BEHAVIAC_NEW CMemberProperty< bool >("SyncSignal", Set_framework_WorldState_SyncSignal, Get_framework_WorldState_SyncSignal));
			meta->RegisterMemberProperty(743044588u, BEHAVIAC_NEW CMemberProperty< unsigned int >("time", Set_framework_WorldState_time, Get_framework_WorldState_time));
			meta->RegisterMethod(2535312399u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_framework_WorldState_NextWave));
			meta->RegisterMethod(3070336447u, BEHAVIAC_NEW CAgentMethod< int >(FunctionPointer_framework_WorldState_PlayerHP));
			meta->RegisterMethod(692130487u, BEHAVIAC_NEW CAgentMethodVoid_1<int>(FunctionPointer_framework_WorldState_SpawnShip));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_framework_WorldState_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_framework_WorldState_VectorAdd));
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<IList&>(FunctionPointer_framework_WorldState_VectorClear));
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CAgentStaticMethod_2< bool, IList&, System::Object& >(FunctionPointer_framework_WorldState_VectorContains));
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CAgentStaticMethod_1< int, IList& >(FunctionPointer_framework_WorldState_VectorLength));
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_framework_WorldState_VectorRemove));

			AgentMeta::Register<behaviac::Agent>("behaviac::Agent");
			AgentMeta::Register<framework::GameObject>("framework::GameObject");
			AgentMeta::Register<framework::Projectile>("framework::Projectile");
			AgentMeta::Register<framework::Ship>("framework::Ship");
			AgentMeta::Register<framework::WorldState>("framework::WorldState");
			AgentMeta::Register<behaviac::EBTStatus>("behaviac::EBTStatus");
			AgentMeta::Register<IList>("IList");
			AgentMeta::Register<System::Object>("System::Object");

			Agent::RegisterInstanceName<framework::WorldState>("framework::WorldState");

			return true;
		}

		virtual bool unLoad()
		{
			AgentMeta::UnRegister<behaviac::Agent>("behaviac::Agent");
			AgentMeta::UnRegister<framework::GameObject>("framework::GameObject");
			AgentMeta::UnRegister<framework::Projectile>("framework::Projectile");
			AgentMeta::UnRegister<framework::Ship>("framework::Ship");
			AgentMeta::UnRegister<framework::WorldState>("framework::WorldState");
			AgentMeta::UnRegister<behaviac::EBTStatus>("behaviac::EBTStatus");
			AgentMeta::UnRegister<IList>("IList");
			AgentMeta::UnRegister<System::Object>("System::Object");

			Agent::UnRegisterInstanceName<framework::WorldState>("framework::WorldState");

			return true;
		}
	};

	CppBehaviorLoaderImplement _cppBehaviorLoaderImplement_;
}
