// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#include "behaviac_agent_meta.h"

namespace behaviac
{
	class CppBehaviorLoaderImplement : CppBehaviorLoader
	{
	public:
		CppBehaviorLoaderImplement()
		{
			AgentMeta::SetInstance(this);
		}

		virtual ~CppBehaviorLoaderImplement()
		{
		}

		virtual bool load()
		{
			AgentMeta::SetTotalSignature(4248495276u);

			AgentMeta* meta = NULL;
			BEHAVIAC_UNUSED_VAR(meta);

			// behaviac::Agent
			meta = BEHAVIAC_NEW AgentMeta(2472787040u);
			AgentMeta::GetAgentMetas()[1770892321u] = meta;
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_behaviac_Agent_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_behaviac_Agent_VectorAdd));
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<IList&>(FunctionPointer_behaviac_Agent_VectorClear));
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CAgentStaticMethod_2< bool, IList&, System::Object& >(FunctionPointer_behaviac_Agent_VectorContains));
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CAgentStaticMethod_1< int, IList& >(FunctionPointer_behaviac_Agent_VectorLength));
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_behaviac_Agent_VectorRemove));

			// Enemy
			meta = BEHAVIAC_NEW AgentMeta(2537493958u);
			AgentMeta::GetAgentMetas()[4123682269u] = meta;
			meta->RegisterMethod(1360866231u, BEHAVIAC_NEW CAgentMethod< int >(FunctionPointer_Enemy_getEnemyType));
			meta->RegisterMethod(1412217555u, BEHAVIAC_NEW CAgentMethod_1< float, float >(FunctionPointer_Enemy_getRandomSpeedByInitSpeed));
			meta->RegisterMethod(2680090406u, BEHAVIAC_NEW CAgentMethod< float >(FunctionPointer_Enemy_getSpeed));
			meta->RegisterMethod(2156114975u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_Enemy_isAlive));
			meta->RegisterMethod(1855126619u, BEHAVIAC_NEW CAgentMethodVoid_1<float>(FunctionPointer_Enemy_setSpeed));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_Enemy_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_Enemy_VectorAdd));
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<IList&>(FunctionPointer_Enemy_VectorClear));
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CAgentStaticMethod_2< bool, IList&, System::Object& >(FunctionPointer_Enemy_VectorContains));
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CAgentStaticMethod_1< int, IList& >(FunctionPointer_Enemy_VectorLength));
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_Enemy_VectorRemove));

			// Hero
			meta = BEHAVIAC_NEW AgentMeta(3578701365u);
			AgentMeta::GetAgentMetas()[4024111892u] = meta;
			meta->RegisterMemberProperty(553786182u, BEHAVIAC_NEW CMemberProperty< bool >("m_isAI", Set_Hero_m_isAI, Get_Hero_m_isAI));
			meta->RegisterMethod(174448843u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Hero_AdjustHeroPosition));
			meta->RegisterMethod(41533270u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Hero_EscapeEnemyCrash));
			meta->RegisterMethod(682563429u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Hero_findAnEnemyAndAttack));
			meta->RegisterMethod(2815222046u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Hero_findAnNearestEnemy));
			meta->RegisterMethod(4192443002u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_Hero_hasEnemyInFrontCanAttack));
			meta->RegisterMethod(1117465715u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_Hero_isWillBeCrashOnNearestEnemy));
			meta->RegisterMethod(3158999171u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_Hero_wait20Frame));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_Hero_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_Hero_VectorAdd));
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<IList&>(FunctionPointer_Hero_VectorClear));
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CAgentStaticMethod_2< bool, IList&, System::Object& >(FunctionPointer_Hero_VectorContains));
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CAgentStaticMethod_1< int, IList& >(FunctionPointer_Hero_VectorLength));
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_Hero_VectorRemove));

			// NPC
			meta = BEHAVIAC_NEW AgentMeta(3044611217u);
			AgentMeta::GetAgentMetas()[2341563425u] = meta;
			meta->RegisterMemberProperty(113313984u, BEHAVIAC_NEW CMemberProperty< int >("Level1Up_Score", Set_NPC_Level1Up_Score, Get_NPC_Level1Up_Score));
			meta->RegisterMemberProperty(3992368067u, BEHAVIAC_NEW CMemberProperty< int >("Level2Up_Score", Set_NPC_Level2Up_Score, Get_NPC_Level2Up_Score));
			meta->RegisterMemberProperty(37017853u, BEHAVIAC_NEW CMemberProperty< int >("Level3Up_Score", Set_NPC_Level3Up_Score, Get_NPC_Level3Up_Score));
			meta->RegisterMemberProperty(3773350788u, BEHAVIAC_NEW CMemberProperty< int >("Level4Up_Score", Set_NPC_Level4Up_Score, Get_NPC_Level4Up_Score));
			meta->RegisterMemberProperty(364290259u, BEHAVIAC_NEW CMemberProperty< bool >("m_canBossRefresh", Set_NPC_m_canBossRefresh, Get_NPC_m_canBossRefresh));
			meta->RegisterMemberProperty(2100198461u, BEHAVIAC_NEW CMemberProperty< int >("m_level", Set_NPC_m_level, Get_NPC_m_level));
			meta->RegisterMethod(1330329059u, BEHAVIAC_NEW CAgentMethod_1< int, int >(FunctionPointer_NPC_getLevel));
			meta->RegisterMethod(3662936423u, BEHAVIAC_NEW CAgentMethodVoid_2<int, int>(FunctionPointer_NPC_setLeveUpScore));
			meta->RegisterMethod(415097791u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_NPC_spawnEnemy));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_NPC_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_NPC_VectorAdd));
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<IList&>(FunctionPointer_NPC_VectorClear));
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CAgentStaticMethod_2< bool, IList&, System::Object& >(FunctionPointer_NPC_VectorContains));
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CAgentStaticMethod_1< int, IList& >(FunctionPointer_NPC_VectorLength));
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_NPC_VectorRemove));

			AgentMeta::Register<behaviac::Agent>("behaviac::Agent");
			AgentMeta::Register<Enemy>("Enemy");
			AgentMeta::Register<Hero>("Hero");
			AgentMeta::Register<NPC>("NPC");
			AgentMeta::Register<ETest>("ETest");
			AgentMeta::Register<IList>("IList");
			AgentMeta::Register<StructTest>("StructTest");

			return true;
		}

		virtual bool unLoad()
		{
			AgentMeta::UnRegister<behaviac::Agent>("behaviac::Agent");
			AgentMeta::UnRegister<Enemy>("Enemy");
			AgentMeta::UnRegister<Hero>("Hero");
			AgentMeta::UnRegister<NPC>("NPC");
			AgentMeta::UnRegister<ETest>("ETest");
			AgentMeta::UnRegister<IList>("IList");
			AgentMeta::UnRegister<StructTest>("StructTest");

			return true;
		}
	};

	CppBehaviorLoaderImplement _cppBehaviorLoaderImplement_;
}
