// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#ifndef BEHAVIAC_AGENT_PROPERTIES_H
#define BEHAVIAC_AGENT_PROPERTIES_H

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"
#include "behaviac_customized_types.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }
	inline void FunctionPointer_behaviac_Agent_VectorAdd(IList& param0, System::Object& param1) { behaviac::Agent::VectorAdd(param0, param1); }
	inline void FunctionPointer_behaviac_Agent_VectorClear(IList& param0) { behaviac::Agent::VectorClear(param0); }
	inline bool FunctionPointer_behaviac_Agent_VectorContains(IList& param0, System::Object& param1) { return behaviac::Agent::VectorContains(param0, param1); }
	inline int FunctionPointer_behaviac_Agent_VectorLength(IList& param0) { return behaviac::Agent::VectorLength(param0); }
	inline void FunctionPointer_behaviac_Agent_VectorRemove(IList& param0, System::Object& param1) { behaviac::Agent::VectorRemove(param0, param1); }
	inline int FunctionPointer_Enemy_getEnemyType(Agent* self) { return (int)((Enemy*)self)->_Execute_Method_<METHOD_TYPE_Enemy_getEnemyType, int >(); }
	inline float FunctionPointer_Enemy_getRandomSpeedByInitSpeed(Agent* self, float param0) { return (float)((Enemy*)self)->_Execute_Method_<METHOD_TYPE_Enemy_getRandomSpeedByInitSpeed, float, float >(param0); }
	inline float FunctionPointer_Enemy_getSpeed(Agent* self) { return (float)((Enemy*)self)->_Execute_Method_<METHOD_TYPE_Enemy_getSpeed, float >(); }
	inline bool FunctionPointer_Enemy_isAlive(Agent* self) { return (bool)((Enemy*)self)->_Execute_Method_<METHOD_TYPE_Enemy_isAlive, bool >(); }
	inline void FunctionPointer_Enemy_setSpeed(Agent* self, float param0) { ((Enemy*)self)->_Execute_Method_<METHOD_TYPE_Enemy_setSpeed, void, float >(param0); }
	inline void FunctionPointer_Enemy_LogMessage(char* param0) { Enemy::LogMessage(param0); }
	inline void FunctionPointer_Enemy_VectorAdd(IList& param0, System::Object& param1) { Enemy::VectorAdd(param0, param1); }
	inline void FunctionPointer_Enemy_VectorClear(IList& param0) { Enemy::VectorClear(param0); }
	inline bool FunctionPointer_Enemy_VectorContains(IList& param0, System::Object& param1) { return Enemy::VectorContains(param0, param1); }
	inline int FunctionPointer_Enemy_VectorLength(IList& param0) { return Enemy::VectorLength(param0); }
	inline void FunctionPointer_Enemy_VectorRemove(IList& param0, System::Object& param1) { Enemy::VectorRemove(param0, param1); }

	inline void Set_Hero_m_isAI(Agent* self, bool value) { ((Hero*)self)->_Get_Property_<PROPERTY_TYPE_Hero_m_isAI, bool >() = value; };
	inline const void* Get_Hero_m_isAI(Agent* self) { return &((Hero*)self)->_Get_Property_<PROPERTY_TYPE_Hero_m_isAI, bool >(); };

	inline void FunctionPointer_Hero_AdjustHeroPosition(Agent* self) { ((Hero*)self)->_Execute_Method_<METHOD_TYPE_Hero_AdjustHeroPosition, void >(); }
	inline void FunctionPointer_Hero_EscapeEnemyCrash(Agent* self) { ((Hero*)self)->_Execute_Method_<METHOD_TYPE_Hero_EscapeEnemyCrash, void >(); }
	inline void FunctionPointer_Hero_findAnEnemyAndAttack(Agent* self) { ((Hero*)self)->_Execute_Method_<METHOD_TYPE_Hero_findAnEnemyAndAttack, void >(); }
	inline void FunctionPointer_Hero_findAnNearestEnemy(Agent* self) { ((Hero*)self)->_Execute_Method_<METHOD_TYPE_Hero_findAnNearestEnemy, void >(); }
	inline bool FunctionPointer_Hero_hasEnemyInFrontCanAttack(Agent* self) { return (bool)((Hero*)self)->_Execute_Method_<METHOD_TYPE_Hero_hasEnemyInFrontCanAttack, bool >(); }
	inline bool FunctionPointer_Hero_isWillBeCrashOnNearestEnemy(Agent* self) { return (bool)((Hero*)self)->_Execute_Method_<METHOD_TYPE_Hero_isWillBeCrashOnNearestEnemy, bool >(); }
	inline bool FunctionPointer_Hero_wait20Frame(Agent* self) { return (bool)((Hero*)self)->_Execute_Method_<METHOD_TYPE_Hero_wait20Frame, bool >(); }
	inline void FunctionPointer_Hero_LogMessage(char* param0) { Hero::LogMessage(param0); }
	inline void FunctionPointer_Hero_VectorAdd(IList& param0, System::Object& param1) { Hero::VectorAdd(param0, param1); }
	inline void FunctionPointer_Hero_VectorClear(IList& param0) { Hero::VectorClear(param0); }
	inline bool FunctionPointer_Hero_VectorContains(IList& param0, System::Object& param1) { return Hero::VectorContains(param0, param1); }
	inline int FunctionPointer_Hero_VectorLength(IList& param0) { return Hero::VectorLength(param0); }
	inline void FunctionPointer_Hero_VectorRemove(IList& param0, System::Object& param1) { Hero::VectorRemove(param0, param1); }

	inline void Set_NPC_Level1Up_Score(Agent* self, int value) { ((NPC*)self)->_Get_Property_<PROPERTY_TYPE_NPC_Level1Up_Score, int >() = value; };
	inline const void* Get_NPC_Level1Up_Score(Agent* self) { return &((NPC*)self)->_Get_Property_<PROPERTY_TYPE_NPC_Level1Up_Score, int >(); };

	inline void Set_NPC_Level2Up_Score(Agent* self, int value) { ((NPC*)self)->_Get_Property_<PROPERTY_TYPE_NPC_Level2Up_Score, int >() = value; };
	inline const void* Get_NPC_Level2Up_Score(Agent* self) { return &((NPC*)self)->_Get_Property_<PROPERTY_TYPE_NPC_Level2Up_Score, int >(); };

	inline void Set_NPC_Level3Up_Score(Agent* self, int value) { ((NPC*)self)->_Get_Property_<PROPERTY_TYPE_NPC_Level3Up_Score, int >() = value; };
	inline const void* Get_NPC_Level3Up_Score(Agent* self) { return &((NPC*)self)->_Get_Property_<PROPERTY_TYPE_NPC_Level3Up_Score, int >(); };

	inline void Set_NPC_Level4Up_Score(Agent* self, int value) { ((NPC*)self)->_Get_Property_<PROPERTY_TYPE_NPC_Level4Up_Score, int >() = value; };
	inline const void* Get_NPC_Level4Up_Score(Agent* self) { return &((NPC*)self)->_Get_Property_<PROPERTY_TYPE_NPC_Level4Up_Score, int >(); };

	inline void Set_NPC_m_canBossRefresh(Agent* self, bool value) { ((NPC*)self)->_Get_Property_<PROPERTY_TYPE_NPC_m_canBossRefresh, bool >() = value; };
	inline const void* Get_NPC_m_canBossRefresh(Agent* self) { return &((NPC*)self)->_Get_Property_<PROPERTY_TYPE_NPC_m_canBossRefresh, bool >(); };

	inline void Set_NPC_m_level(Agent* self, int value) { ((NPC*)self)->_Get_Property_<PROPERTY_TYPE_NPC_m_level, int >() = value; };
	inline const void* Get_NPC_m_level(Agent* self) { return &((NPC*)self)->_Get_Property_<PROPERTY_TYPE_NPC_m_level, int >(); };

	inline int FunctionPointer_NPC_getLevel(Agent* self, int param0) { return (int)((NPC*)self)->_Execute_Method_<METHOD_TYPE_NPC_getLevel, int, int >(param0); }
	inline void FunctionPointer_NPC_setLeveUpScore(Agent* self, int param0, int param1) { ((NPC*)self)->_Execute_Method_<METHOD_TYPE_NPC_setLeveUpScore, void, int, int >(param0, param1); }
	inline void FunctionPointer_NPC_spawnEnemy(Agent* self) { ((NPC*)self)->_Execute_Method_<METHOD_TYPE_NPC_spawnEnemy, void >(); }
	inline void FunctionPointer_NPC_LogMessage(char* param0) { NPC::LogMessage(param0); }
	inline void FunctionPointer_NPC_VectorAdd(IList& param0, System::Object& param1) { NPC::VectorAdd(param0, param1); }
	inline void FunctionPointer_NPC_VectorClear(IList& param0) { NPC::VectorClear(param0); }
	inline bool FunctionPointer_NPC_VectorContains(IList& param0, System::Object& param1) { return NPC::VectorContains(param0, param1); }
	inline int FunctionPointer_NPC_VectorLength(IList& param0) { return NPC::VectorLength(param0); }
	inline void FunctionPointer_NPC_VectorRemove(IList& param0, System::Object& param1) { NPC::VectorRemove(param0, param1); }
}
#endif // BEHAVIAC_AGENT_PROPERTIES_H
