// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#ifndef BEHAVIAC_HEADERS_H
#define BEHAVIAC_HEADERS_H

#include "behaviac/behaviac.h"

// You should set the agent header files of your game when exporting cpp files on the behaviac editor:

// The following agent header files is generated automatically:

#endif // BEHAVIAC_HEADERS_H
