// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#include "behaviac_agent_meta.h"

namespace behaviac
{
	class CppBehaviorLoaderImplement : CppBehaviorLoader
	{
	public:
		CppBehaviorLoaderImplement()
		{
			AgentMeta::SetInstance(this);
		}

		virtual ~CppBehaviorLoaderImplement()
		{
		}

		virtual bool load()
		{
			AgentMeta::SetTotalSignature(460624040u);

			AgentMeta* meta = NULL;
			BEHAVIAC_UNUSED_VAR(meta);

			// behaviac::Agent
			meta = BEHAVIAC_NEW AgentMeta(2472787040u);
			AgentMeta::GetAgentMetas()[1770892321u] = meta;
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_behaviac_Agent_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_behaviac_Agent_VectorAdd));
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<IList&>(FunctionPointer_behaviac_Agent_VectorClear));
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CAgentStaticMethod_2< bool, IList&, System::Object& >(FunctionPointer_behaviac_Agent_VectorContains));
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CAgentStaticMethod_1< int, IList& >(FunctionPointer_behaviac_Agent_VectorLength));
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_behaviac_Agent_VectorRemove));

			// CBTPlayer
			meta = BEHAVIAC_NEW AgentMeta(2158685900u);
			AgentMeta::GetAgentMetas()[2361377009u] = meta;
			meta->RegisterMemberProperty(3476008754u, BEHAVIAC_NEW CMemberProperty< unsigned int >("m_iBaseSpeed", Set_CBTPlayer_m_iBaseSpeed, Get_CBTPlayer_m_iBaseSpeed));
			meta->RegisterMethod(3088088344u, BEHAVIAC_NEW CAgentMethod< behaviac::EBTStatus >(FunctionPointer_CBTPlayer_Action1));
			meta->RegisterMethod(2317754266u, BEHAVIAC_NEW CAgentMethod< behaviac::EBTStatus >(FunctionPointer_CBTPlayer_Action3));
			meta->RegisterMethod(4094979492u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_CBTPlayer_Condition));
			meta->RegisterMethod(398261213u, BEHAVIAC_NEW CAgentMethodVoid_1<int>(FunctionPointer_CBTPlayer_MoveAhead));
			meta->RegisterMethod(2341147270u, BEHAVIAC_NEW CAgentMethodVoid_1<int>(FunctionPointer_CBTPlayer_MoveBack));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_CBTPlayer_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_CBTPlayer_VectorAdd));
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<IList&>(FunctionPointer_CBTPlayer_VectorClear));
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CAgentStaticMethod_2< bool, IList&, System::Object& >(FunctionPointer_CBTPlayer_VectorContains));
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CAgentStaticMethod_1< int, IList& >(FunctionPointer_CBTPlayer_VectorLength));
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CAgentStaticMethodVoid_2<IList&, System::Object&>(FunctionPointer_CBTPlayer_VectorRemove));

			AgentMeta::Register<behaviac::Agent>("behaviac::Agent");
			AgentMeta::Register<CBTPlayer>("CBTPlayer");
			AgentMeta::Register<behaviac::EBTStatus>("behaviac::EBTStatus");
			AgentMeta::Register<IList>("IList");

			Agent::RegisterInstanceName<CBTPlayer>("player1");

			return true;
		}

		virtual bool unLoad()
		{
			AgentMeta::UnRegister<behaviac::Agent>("behaviac::Agent");
			AgentMeta::UnRegister<CBTPlayer>("CBTPlayer");
			AgentMeta::UnRegister<behaviac::EBTStatus>("behaviac::EBTStatus");
			AgentMeta::UnRegister<IList>("IList");

			Agent::UnRegisterInstanceName<CBTPlayer>("player1");

			return true;
		}
	};

	CppBehaviorLoaderImplement _cppBehaviorLoaderImplement_;
}
