// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#include "behaviac/behaviac.h"

#include "behaviac_generated_behaviors.h"

namespace behaviac
{
	class CppGenerationManager : GenerationManager
	{
	public:
		CppGenerationManager()
		{
			SetInstance(this);
		}

		virtual void RegisterBehaviorsImplement()
		{
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("base/boring", bt_base_boring::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("base/homing", bt_base_homing::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("base/slowboring", bt_base_slowboring::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("base/sync_homing", bt_base_sync_homing::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("projectile/projectile_test", bt_projectile_projectile_test::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("ships/0_basic", bt_ships_0_basic::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("ships/1_1_suicide", bt_ships_1_1_suicide::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("ships/1_2_suicide", bt_ships_1_2_suicide::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("ships/1_3_suicide", bt_ships_1_3_suicide::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("ships/2_basic_probability", bt_ships_2_basic_probability::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("ships/3_basic_move", bt_ships_3_basic_move::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("ships/4_destroy_projectiles", bt_ships_4_destroy_projectiles::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("ships/5_group", bt_ships_5_group::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("ships/6_director", bt_ships_6_director::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("ships/7_signal", bt_ships_7_signal::Create);
		}
	};

	CppGenerationManager _cppGenerationManager_;
}
