// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#include "../types/behaviac_types.h"

namespace behaviac
{
	class bt_node_test_circular_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_condition_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_condition_ut_1
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_condition_ut_2
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_condition_ut_3
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_decoration_alwaysfailure_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_decoration_alwaysrunning_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_decoration_alwayssuccess_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_decoration_countlimit_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_decoration_countlimit_ut_1
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_decoration_countlimit_ut_2
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_decoration_countlimit_ut_3
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_decoration_failureuntil_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_decoration_failureuntil_ut_1
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

}
