// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#include "../types/behaviac_types.h"

namespace behaviac
{
	class bt_node_test_enter_exit_action_ut_2
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_event_subtree_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_event_subtree_1
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_event_subtree_2
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_event_subtree_3
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_event_subtree_4
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_event_subtree_5
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_event_subtree_6
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_event_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_event_ut_1
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_event_ut_2
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_event_ut_3
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_event_ut_4
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_frames_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

}
