// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers

namespace behaviac
{
	struct METHOD_TYPE_behaviac_Agent_LogMessage { };
	template<> inline void Agent::_Execute_Method_<METHOD_TYPE_behaviac_Agent_LogMessage>(char* p0)
	{
		this->behaviac::Agent::LogMessage(p0);
	}

	struct METHOD_TYPE_behaviac_Agent_VectorAdd { };
	template<> inline void Agent::_Execute_Method_<METHOD_TYPE_behaviac_Agent_VectorAdd>(IList& p0, System::Object& p1)
	{
		this->behaviac::Agent::VectorAdd(p0, p1);
	}

	struct METHOD_TYPE_behaviac_Agent_VectorClear { };
	template<> inline void Agent::_Execute_Method_<METHOD_TYPE_behaviac_Agent_VectorClear>(IList& p0)
	{
		this->behaviac::Agent::VectorClear(p0);
	}

	struct METHOD_TYPE_behaviac_Agent_VectorContains { };
	template<> inline bool Agent::_Execute_Method_<METHOD_TYPE_behaviac_Agent_VectorContains>(IList& p0, System::Object& p1)
	{
		return this->behaviac::Agent::VectorContains(p0, p1);
	}

	struct METHOD_TYPE_behaviac_Agent_VectorLength { };
	template<> inline int Agent::_Execute_Method_<METHOD_TYPE_behaviac_Agent_VectorLength>(IList& p0)
	{
		return this->behaviac::Agent::VectorLength(p0);
	}

	struct METHOD_TYPE_behaviac_Agent_VectorRemove { };
	template<> inline void Agent::_Execute_Method_<METHOD_TYPE_behaviac_Agent_VectorRemove>(IList& p0, System::Object& p1)
	{
		this->behaviac::Agent::VectorRemove(p0, p1);
	}

}

struct PROPERTY_TYPE_CBTPlayer_m_iBaseSpeed { };
template<> inline unsigned int& CBTPlayer::_Get_Property_<PROPERTY_TYPE_CBTPlayer_m_iBaseSpeed>()
{
	unsigned char* pc = (unsigned char*)this;
	pc += (int)BEHAVIAC_OFFSETOF(CBTPlayer, CBTPlayer::m_iBaseSpeed);
	return *(reinterpret_cast<unsigned int*>(pc));
}

struct METHOD_TYPE_CBTPlayer_Action1 { };
template<> inline behaviac::EBTStatus CBTPlayer::_Execute_Method_<METHOD_TYPE_CBTPlayer_Action1>()
{
	return this->CBTPlayer::Action1();
}

struct METHOD_TYPE_CBTPlayer_Action3 { };
template<> inline behaviac::EBTStatus CBTPlayer::_Execute_Method_<METHOD_TYPE_CBTPlayer_Action3>()
{
	return this->CBTPlayer::Action3();
}

struct METHOD_TYPE_CBTPlayer_Condition { };
template<> inline bool CBTPlayer::_Execute_Method_<METHOD_TYPE_CBTPlayer_Condition>()
{
	return this->CBTPlayer::Condition();
}

#endif // _BEHAVIAC_MEMBER_VISITOR_H_
