// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class FirstAgent : behaviac.Agent
{
	private bool p1 = false;
	public void _set_p1(bool value)
	{
		p1 = value;
	}
	public bool _get_p1()
	{
		return p1;
	}

	private int p2 = 0;
	public void _set_p2(int value)
	{
		p2 = value;
	}
	public int _get_p2()
	{
		return p2;
	}

	private float p3 = 0;
	public void _set_p3(float value)
	{
		p3 = value;
	}
	public float _get_p3()
	{
		return p3;
	}

}
