// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }

	inline void Set_FirstAgent_p1(Agent* self, bool value) { ((FirstAgent*)self)->_set_p1(value); };
	inline const void* Get_FirstAgent_p1(Agent* self) { return &((FirstAgent*)self)->_get_p1(); };

	inline void Set_FirstAgent_p2(Agent* self, int value) { ((FirstAgent*)self)->_set_p2(value); };
	inline const void* Get_FirstAgent_p2(Agent* self) { return &((FirstAgent*)self)->_get_p2(); };

	inline void Set_FirstAgent_p3(Agent* self, float value) { ((FirstAgent*)self)->_set_p3(value); };
	inline const void* Get_FirstAgent_p3(Agent* self) { return &((FirstAgent*)self)->_get_p3(); };

	inline void FunctionPointer_FirstAgent_LogMessage(char* param0) { FirstAgent::LogMessage(param0); }
	inline bool FunctionPointer_FirstAgent_m2(Agent* self) { return ((FirstAgent*)self)->m2(); }
	inline void FunctionPointer_FirstAgent_SayHello(Agent* self) { ((FirstAgent*)self)->SayHello(); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
