// ---------------------------------------------------------------------
// This agent file is auto-generated by behaviac designer,
// so you should not modify it manually, instead of by the designer.
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_FIRSTAGENT_H_
#define _BEHAVIAC_FIRSTAGENT_H_

#include "behaviac_agent_headers.h"

class FirstAgent : public behaviac::Agent
{
public:
	FirstAgent();
	virtual ~FirstAgent();

	BEHAVIAC_DECLARE_AGENTTYPE(FirstAgent, behaviac::Agent)

private:
	bool p1;
public:
	inline void _set_p1(bool value)
	{
		p1 = value;
	}
	inline bool& _get_p1()
	{
		return p1;
	}

private:
	int p2;
public:
	inline void _set_p2(int value)
	{
		p2 = value;
	}
	inline int& _get_p2()
	{
		return p2;
	}

private:
	float p3;
public:
	inline void _set_p3(float value)
	{
		p3 = value;
	}
	inline float& _get_p3()
	{
		return p3;
	}

public:
	bool m2();

public:
	void SayHello();

#include "FirstAgent.inc"
};

#endif
