// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }

	inline void Set_CPerformanceAgent_DistanceToEnemy(Agent* self, float value) { ((CPerformanceAgent*)self)->DistanceToEnemy = value; };
	inline const void* Get_CPerformanceAgent_DistanceToEnemy(Agent* self) { return &((CPerformanceAgent*)self)->DistanceToEnemy; };

	inline void Set_CPerformanceAgent_Food(Agent* self, float value) { ((CPerformanceAgent*)self)->Food = value; };
	inline const void* Get_CPerformanceAgent_Food(Agent* self) { return &((CPerformanceAgent*)self)->Food; };

	inline void Set_CPerformanceAgent_HP(Agent* self, float value) { ((CPerformanceAgent*)self)->HP = value; };
	inline const void* Get_CPerformanceAgent_HP(Agent* self) { return &((CPerformanceAgent*)self)->HP; };

	inline void Set_CPerformanceAgent_Hungry(Agent* self, float value) { ((CPerformanceAgent*)self)->Hungry = value; };
	inline const void* Get_CPerformanceAgent_Hungry(Agent* self) { return &((CPerformanceAgent*)self)->Hungry; };

	inline behaviac::EBTStatus FunctionPointer_CPerformanceAgent_Eat(Agent* self) { return ((CPerformanceAgent*)self)->Eat(); }
	inline behaviac::EBTStatus FunctionPointer_CPerformanceAgent_Fidget(Agent* self) { return ((CPerformanceAgent*)self)->Fidget(); }
	inline void FunctionPointer_CPerformanceAgent_Fire(Agent* self) { ((CPerformanceAgent*)self)->Fire(); }
	inline behaviac::EBTStatus FunctionPointer_CPerformanceAgent_RunAway(Agent* self) { return ((CPerformanceAgent*)self)->RunAway(); }
	inline behaviac::EBTStatus FunctionPointer_CPerformanceAgent_SearchForFood(Agent* self) { return ((CPerformanceAgent*)self)->SearchForFood(); }
	inline behaviac::EBTStatus FunctionPointer_CPerformanceAgent_Wander(Agent* self) { return ((CPerformanceAgent*)self)->Wander(); }
	inline void FunctionPointer_CPerformanceAgent_LogMessage(char* param0) { CPerformanceAgent::LogMessage(param0); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
